=== gsauthof/openmensa/open-mensa-v2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://openmensa.org/open-mensa-v2" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://openmensa.org/open-mensa-v2" elementFormDefault="qualified">

    <xs:element name="openmensa" type="openmensaType"></xs:element>
    
    <xs:complexType name="openmensaType">
        <xs:annotation>
        	<xs:documentation>This is the required OpenMense root element always accompanied by a version attribute that explicitly tells the feed's version to the parser.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
    		<xs:element name="canteen" type="canteenType">
    		</xs:element>
    	</xs:sequence>
    	<xs:attribute name="version" type="xs:float" use="required">
    		<xs:annotation>
    			<xs:documentation>The version should be equal to 2.0.</xs:documentation>
    		</xs:annotation></xs:attribute>
    </xs:complexType>

    <xs:complexType name="canteenType">
        <xs:annotation>
        	<xs:documentation>This stands for a single canteen.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="day" type="dayType" maxOccurs="unbounded"
    			minOccurs="0">
                <xs:annotation>
                	<xs:documentation>All meals of all categories are grouped by day. There may be no day elements at all - that's ok because for some days there are no meals.</xs:documentation>
                </xs:annotation>
            </xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="dayType">
        <xs:choice>
        	<xs:element name="category" type="categoryType"
        		maxOccurs="unbounded" minOccurs="1">
        		<xs:annotation>
        			<xs:documentation>Every meal must belong to a category so there should be at least one category since a day without any meals may be omitted completely else.</xs:documentation>
        		</xs:annotation>
        	</xs:element>
        	<xs:element name="closed">
                <xs:annotation>
                	<xs:documentation>Indicates that for the given day a canteen has closed (to distinguish from the case where there is - for some reason - no data). Should be used on weekends or explicit closing times on holidays.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
        			<xs:restriction base="xs:string">
        				<xs:maxLength value="0"></xs:maxLength>
        			</xs:restriction>
        		</xs:simpleType>
        	</xs:element>
        </xs:choice>
    	<xs:attribute name="date" use="required">
            <xs:annotation>
            	<xs:documentation>This field specifies the date of the day as "YYYY-MM-DD.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
                <xs:annotation>
                	<xs:documentation></xs:documentation>
                </xs:annotation>
                <xs:restriction base="xs:string">
    				<xs:pattern
    					value="[0-9]{4,4}-[0-9]{2,2}-[0-9]{2,2}">
    				</xs:pattern>
    			</xs:restriction>
    		</xs:simpleType>
    	</xs:attribute>
    </xs:complexType>

    <xs:complexType name="categoryType">
    	<xs:sequence>
    		<xs:element name="meal" type="mealType" maxOccurs="unbounded" minOccurs="1">
    			<xs:annotation>
    				<xs:documentation>Each category must contain at least one meal because else the category is useless.</xs:documentation>
    			</xs:annotation></xs:element>
    	</xs:sequence>
    	<xs:attribute name="name" use="required">
            <xs:annotation>
            	<xs:documentation>The name of the category, e.g. "Essen 1" or "Ausgabe A".</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
            	<xs:restriction base="xs:string">
            		<xs:minLength value="1"></xs:minLength>
            		<xs:maxLength value="250"></xs:maxLength>
            	</xs:restriction>
            </xs:simpleType>
    	</xs:attribute>
    </xs:complexType>

    <xs:complexType name="mealType">
    	<xs:sequence>
    		<xs:element name="name">
    			<xs:annotation>
    				<xs:documentation>The name of the meal, e.g. "Rinderhacksteak mit Kartoffeln". Shouldn't be more than a couple of words or a sentence in maximum. Additional text may go into several notes.</xs:documentation>
    			</xs:annotation>
    			<xs:simpleType>
    				<xs:restriction base="xs:string">
    					<xs:minLength value="1"></xs:minLength>
    					<xs:maxLength value="250"></xs:maxLength>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="note" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                	<xs:documentation>A note often resembles a properties of the associated meal like the ingredients used or some important annotations.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                	<xs:restriction base="xs:string">
                		<xs:minLength value="1"></xs:minLength>
                		<xs:maxLength value="250"></xs:maxLength>
                	</xs:restriction>
                </xs:simpleType>
    		</xs:element>
    		<xs:element name="price" maxOccurs="unbounded" minOccurs="0" type="priceType">
                <xs:annotation>
                	<xs:documentation>This field contains a price in euro for a given role (because different prices may apply different groups of people). There mustn't be two price elements with the same role for a meal!</xs:documentation>
                </xs:annotation>
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="priceType">
    	<xs:simpleContent>
    		<xs:extension base="xs:float">
    			<xs:attribute name="role" use="required">
                    <xs:annotation>
                    	<xs:documentation>A price's role defines for which group of persons the price is valid:
- pupils (some canteens do that)
- students
- employees (of your organization) or
- others (people that do not belong to your organization or to any other group listed here).</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                    	<xs:restriction base="xs:string">
                    		<xs:enumeration value="pupil"></xs:enumeration>
                    		<xs:enumeration value="student"></xs:enumeration>
                    		<xs:enumeration value="employee"></xs:enumeration>
                    		<xs:enumeration value="other"></xs:enumeration>
                    	</xs:restriction>
                    </xs:simpleType>
    			</xs:attribute>
    		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== gsauthof/openmensa/test/ref/wiesbaden_accent_20150127.xml
<?xml version="1.0" encoding="UTF-8"?>
<openmensa version="2.0"
           xmlns="http://openmensa.org/open-mensa-v2"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://openmensa.org/open-mensa-v2 http://openmensa.org/open-mensa-v2.xsd">
  <canteen>
    <day date='2015-01-26'>
      <category name='Essen 1'>
        <meal>
          <name>Kartoffelsuppe</name>
          <note>(1, 2, 3, 5, G, I, L)</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Pizza Birne-Camembert</name>
          <note>(1, 2, A, G)</note>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Pizza Salami</name>
          <note>(1, 2, 3, 4, 5, 6, A, G, I, J, 9)</note>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Sojabratwurst</name>
          <note>mit Zwiebelsauce und einer Beilage nach Wahl (A, C, F, J)</note>
          <price role='student'>1.60</price>
          <price role='employee'>3.2</price>
          <price role='other'>3.2</price>
        </meal>
      </category>
      <category name='Essen 5'>
        <meal>
          <name>Spaghetti</name>
          <note>mit Sauce Bolognese und einer Beilage nach Wahl (A)</note>
          <price role='student'>2.60</price>
          <price role='employee'>4.2</price>
          <price role='other'>4.2</price>
        </meal>
      </category>
    </day>
    <day date='2015-01-27'>
      <category name='Essen 1'>
        <meal>
          <name>Bifteki</name>
          <note>mit Paprika-Tomatensauce und zwei Beilagen nach Wahl (A, C, F, G)</note>
          <price role='student'>3.50</price>
          <price role='employee'>5.1</price>
          <price role='other'>5.1</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Gemüse-Haferpfanne</name>
          <note>mit einer Beilage nach Wahl (A, I, J)</note>
          <price role='student'>1.60</price>
          <price role='employee'>3.2</price>
          <price role='other'>3.2</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Pilzcremesuppe</name>
          <note>(G, L)</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Pizza Mexico</name>
          <note>(1, 2, 3, 4, A, G, I)</note>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 5'>
        <meal>
          <name>Pizza Schinken-Bergkäse</name>
          <note>(1, 2, 3, A, G)</note>
          <price role='student'>4.30</price>
          <price role='employee'>5.9</price>
          <price role='other'>5.9</price>
        </meal>
      </category>
    </day>
    <day date='2015-01-28'>
      <category name='Essen 1'>
        <meal>
          <name>Makkaroni mit Paprikasahne, Hüttenkäse</name>
          <note>und einer Beilage nach Wahl (A, G)</note>
          <price role='student'>2.20</price>
          <price role='employee'>3.8</price>
          <price role='other'>3.8</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Panierte Hähnchenbrust mit Apfel-Ananasfüllung</name>
          <note>mit Curry-Fruchtsauce und zwei Beilagen nach Wahl (A, G)</note>
          <price role='student'>3.60</price>
          <price role='employee'>5.2</price>
          <price role='other'>5.2</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Pizza Cabanossi</name>
          <note>(1, 2, 3, 4, 5, 6, 8, A, G, J)</note>
          <price role='student'>4.00</price>
          <price role='employee'>5.6</price>
          <price role='other'>5.6</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Pizza Champignons</name>
          <note>(1, 2, 3, 4, 5, A, G, L)</note>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 5'>
        <meal>
          <name>Tschechische Knoblauch-Kartoffelsuppe</name>
          <note>(5, G, I, L)</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
    </day>
    <day date='2015-01-29'>
      <category name='Essen 1'>
        <meal>
          <name>Aloo Gobi</name>
          <note>mit einer Beilage nach Wahl (5)</note>
          <price role='student'>1.70</price>
          <price role='employee'>3.3</price>
          <price role='other'>3.3</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Ciabattaburger mit Rosmarinmayonnaise</name>
          <note>und Country Potatoes (1, A, C, F, G, H, I, J)</note>
          <price role='student'>4.20</price>
          <price role='employee'>5.8</price>
          <price role='other'>5.8</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Pizza Hähnchen-Ananas</name>
          <note>(1, 2, 3, 4, 5, 6, 8, A, D, F, G, J, L)</note>
          <price role='student'>4.30</price>
          <price role='employee'>5.9</price>
          <price role='other'>5.9</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Pizza Margherita</name>
          <note>(1, 2, A, G)</note>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 5'>
        <meal>
          <name>Spinatcremesuppe</name>
          <note>(1, 2, G, I, L)</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
    </day>
    <day date='2015-01-30'>
      <category name='Essen 1'>
        <meal>
          <name>Gemüse-Kartoffelsuppe</name>
          <note>(5, F, G, I)</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Kartoffelrösti mit Mozzarella, Lauch</name>
          <note>und einer Beilage nach Wahl (G)</note>
          <price role='student'>2.60</price>
          <price role='employee'>4.2</price>
          <price role='other'>4.2</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Pizza Gorgonzola-Spinat</name>
          <note>(1, 2, A, G)</note>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Pizza Peppone</name>
          <note>(1, 2, 3, 4, 5, 6, 8, A, G, J)</note>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 5'>
        <meal>
          <name>Schlemmerfilet Italiano</name>
          <note>mit Sauce Vegetale und einer Beilage nach Wahl (A, D, G)</note>
          <price role='student'>3.60</price>
          <price role='employee'>5.2</price>
          <price role='other'>5.2</price>
        </meal>
      </category>
    </day>

  </canteen>
</openmensa>

=== gsauthof/openmensa/test/ref/fhrus_20170303.xml
<?xml version="1.0" encoding="UTF-8"?>
<openmensa version="2.0"
           xmlns="http://openmensa.org/open-mensa-v2"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://openmensa.org/open-mensa-v2 http://openmensa.org/open-mensa-v2.xsd">
  <canteen>
    <day date='2015-03-03'>
      <category name='Essen 1'>
        <meal>
          <name>Tschechische Knoblauch-Kartoffelsuppe</name>
          <note>vegetarisch</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Spinat mit roten Linsen</name>
          <note>mit einer Beilage nach Wahl</note>
          <note>Vegan</note>
          <price role='student'>1.60</price>
          <price role='employee'>3.2</price>
          <price role='other'>3.2</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Paniertes Schollenfilet</name>
          <note>mit Remouladensauce (1, 2, 9, A, C, F, G, J) und zwei Beilagen nach Wahl</note>
          <note>MSC-Fisch</note>
          <price role='student'>4.40</price>
          <price role='employee'>6</price>
          <price role='other'>6</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Matjesfilet</name>
          <note>mit Sauce nach Hausfrauenart (2, 9, G) und einer Beilage nach Wahl</note>
          <note>MSC-Fisch</note>
          <price role='student'>3.00</price>
          <price role='employee'>4.6</price>
          <price role='other'>4.6</price>
        </meal>
      </category>
    </day>
    <day date='2015-03-06'>
      <category name='Essen 1'>
        <meal>
          <name>Kohlrabicremesuppe</name>
          <note>vegetarisch</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Broccoliauflauf</name>
          <note>mit einer Beilage nach Wahl</note>
          <note>vegetarisch</note>
          <price role='student'>3.00</price>
          <price role='employee'>4.6</price>
          <price role='other'>4.6</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Oberhessische Kartoffelsuppe</name>
          <note>mit Wiener Würstchen (2, 3, I) und einem Kaiserbrötchen (A)</note>
          <note>Schwein</note>
          <note>Rind</note>
          <price role='student'>1.80</price>
          <price role='employee'>3.4</price>
          <price role='other'>3.4</price>
        </meal>
      </category>
    </day>
    <day date='2015-03-07'>
      <category name='Essen 1'>
        <meal>
          <name>Spinatcremesuppe</name>
          <note>vegetarisch</note>
          <note>Alkohol</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Sojageschnetzeltes Indonesische Art</name>
          <note>mit einer Beilage nach Wahl</note>
          <note>Vegan</note>
          <price role='student'>2.00</price>
          <price role='employee'>3.6</price>
          <price role='other'>3.6</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Gefüllte Paprikaschote</name>
          <note>mit Tomatensauce und zwei Beilagen nach Wahl</note>
          <note>Geflügel</note>
          <price role='student'>3.50</price>
          <price role='employee'>5.1</price>
          <price role='other'>5.1</price>
        </meal>
      </category>
    </day>
    <day date='2015-03-08'>
      <category name='Essen 1'>
        <meal>
          <name>Ingwer-Karottencremesuppe</name>
          <note>vegetarisch</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Germknödel</name>
          <note>mit Vanillesauce (G) und einer Beilage nach Wahl</note>
          <note>vegetarisch</note>
          <price role='student'>2.40</price>
          <price role='employee'>4</price>
          <price role='other'>4</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Königsberger Klopse</name>
          <note>mit einer Beilage nach Wahl</note>
          <note>Schwein</note>
          <note>Rind</note>
          <price role='student'>3.20</price>
          <price role='employee'>4.8</price>
          <price role='other'>4.8</price>
        </meal>
      </category>
    </day>
    <day date='2015-03-09'>
      <category name='Essen 1'>
        <meal>
          <name>Tschechische Knoblauch-Kartoffelsuppe</name>
          <note>vegetarisch</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Gemüseschnitzel</name>
          <note>mit Tomatensauce und einer Beilage nach Wahl</note>
          <note>Vegan</note>
          <price role='student'>1.60</price>
          <price role='employee'>3.2</price>
          <price role='other'>3.2</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Putengyros</name>
          <note>mit Tzatziki (G) und einer Beilage nach Wahl</note>
          <price role='student'>4.20</price>
          <price role='employee'>5.8</price>
          <price role='other'>5.8</price>
        </meal>
      </category>
    </day>
    <day date='2015-03-10'>
      <category name='Essen 1'>
        <meal>
          <name>Tomatencremesuppe</name>
          <note>vegetarisch</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Gemüsepaella</name>
          <note>mit Tomatensauce und einer Beilage nach Wahl</note>
          <note>Vegan</note>
          <price role='student'>1.80</price>
          <price role='employee'>3.4</price>
          <price role='other'>3.4</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Hokifilet mit Blattspinat</name>
          <note>mit einer Beilage nach Wahl</note>
          <note>MSC-Fisch</note>
          <price role='student'>3.80</price>
          <price role='employee'>5.4</price>
          <price role='other'>5.4</price>
        </meal>
      </category>
    </day>

  </canteen>
</openmensa>
