=== gsauthof/openmensa/open-mensa-v2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://openmensa.org/open-mensa-v2" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://openmensa.org/open-mensa-v2" elementFormDefault="qualified">

    <xs:element name="openmensa" type="openmensaType"></xs:element>
    
    <xs:complexType name="openmensaType">
        <xs:annotation>
        	<xs:documentation>This is the required OpenMense root element always accompanied by a version attribute that explicitly tells the feed's version to the parser.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
    		<xs:element name="canteen" type="canteenType">
    		</xs:element>
    	</xs:sequence>
    	<xs:attribute name="version" type="xs:float" use="required">
    		<xs:annotation>
    			<xs:documentation>The version should be equal to 2.0.</xs:documentation>
    		</xs:annotation></xs:attribute>
    </xs:complexType>

    <xs:complexType name="canteenType">
        <xs:annotation>
        	<xs:documentation>This stands for a single canteen.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="day" type="dayType" maxOccurs="unbounded"
    			minOccurs="0">
                <xs:annotation>
                	<xs:documentation>All meals of all categories are grouped by day. There may be no day elements at all - that's ok because for some days there are no meals.</xs:documentation>
                </xs:annotation>
            </xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="dayType">
        <xs:choice>
        	<xs:element name="category" type="categoryType"
        		maxOccurs="unbounded" minOccurs="1">
        		<xs:annotation>
        			<xs:documentation>Every meal must belong to a category so there should be at least one category since a day without any meals may be omitted completely else.</xs:documentation>
        		</xs:annotation>
        	</xs:element>
        	<xs:element name="closed">
                <xs:annotation>
                	<xs:documentation>Indicates that for the given day a canteen has closed (to distinguish from the case where there is - for some reason - no data). Should be used on weekends or explicit closing times on holidays.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
        			<xs:restriction base="xs:string">
        				<xs:maxLength value="0"></xs:maxLength>
        			</xs:restriction>
        		</xs:simpleType>
        	</xs:element>
        </xs:choice>
    	<xs:attribute name="date" use="required">
            <xs:annotation>
            	<xs:documentation>This field specifies the date of the day as "YYYY-MM-DD.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
                <xs:annotation>
                	<xs:documentation></xs:documentation>
                </xs:annotation>
                <xs:restriction base="xs:string">
    				<xs:pattern
    					value="[0-9]{4,4}-[0-9]{2,2}-[0-9]{2,2}">
    				</xs:pattern>
    			</xs:restriction>
    		</xs:simpleType>
    	</xs:attribute>
    </xs:complexType>

    <xs:complexType name="categoryType">
    	<xs:sequence>
    		<xs:element name="meal" type="mealType" maxOccurs="unbounded" minOccurs="1">
    			<xs:annotation>
    				<xs:documentation>Each category must contain at least one meal because else the category is useless.</xs:documentation>
    			</xs:annotation></xs:element>
    	</xs:sequence>
    	<xs:attribute name="name" use="required">
            <xs:annotation>
            	<xs:documentation>The name of the category, e.g. "Essen 1" or "Ausgabe A".</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
            	<xs:restriction base="xs:string">
            		<xs:minLength value="1"></xs:minLength>
            		<xs:maxLength value="250"></xs:maxLength>
            	</xs:restriction>
            </xs:simpleType>
    	</xs:attribute>
    </xs:complexType>

    <xs:complexType name="mealType">
    	<xs:sequence>
    		<xs:element name="name">
    			<xs:annotation>
    				<xs:documentation>The name of the meal, e.g. "Rinderhacksteak mit Kartoffeln". Shouldn't be more than a couple of words or a sentence in maximum. Additional text may go into several notes.</xs:documentation>
    			</xs:annotation>
    			<xs:simpleType>
    				<xs:restriction base="xs:string">
    					<xs:minLength value="1"></xs:minLength>
    					<xs:maxLength value="250"></xs:maxLength>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="note" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                	<xs:documentation>A note often resembles a properties of the associated meal like the ingredients used or some important annotations.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                	<xs:restriction base="xs:string">
                		<xs:minLength value="1"></xs:minLength>
                		<xs:maxLength value="250"></xs:maxLength>
                	</xs:restriction>
                </xs:simpleType>
    		</xs:element>
    		<xs:element name="price" maxOccurs="unbounded" minOccurs="0" type="priceType">
                <xs:annotation>
                	<xs:documentation>This field contains a price in euro for a given role (because different prices may apply different groups of people). There mustn't be two price elements with the same role for a meal!</xs:documentation>
                </xs:annotation>
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="priceType">
    	<xs:simpleContent>
    		<xs:extension base="xs:float">
    			<xs:attribute name="role" use="required">
                    <xs:annotation>
                    	<xs:documentation>A price's role defines for which group of persons the price is valid:
- pupils (some canteens do that)
- students
- employees (of your organization) or
- others (people that do not belong to your organization or to any other group listed here).</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                    	<xs:restriction base="xs:string">
                    		<xs:enumeration value="pupil"></xs:enumeration>
                    		<xs:enumeration value="student"></xs:enumeration>
                    		<xs:enumeration value="employee"></xs:enumeration>
                    		<xs:enumeration value="other"></xs:enumeration>
                    	</xs:restriction>
                    </xs:simpleType>
    			</xs:attribute>
    		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== gsauthof/openmensa/test/ref/fhrus_attr_var.xml
<?xml version="1.0" encoding="UTF-8"?>
<openmensa version="2.0"
           xmlns="http://openmensa.org/open-mensa-v2"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://openmensa.org/open-mensa-v2 http://openmensa.org/open-mensa-v2.xsd">
  <canteen>
    <day date='2015-02-02'>
      <category name='Essen 1'>
        <meal>
          <name>Aloo Gobi</name>
          <note>und einer Beilage nach Wahl (5)</note>
          <price role='student'>1.60</price>
          <price role='employee'>3.2</price>
          <price role='other'>3.2</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Ebly-Gemüsepfanne</name>
          <note>und einer Beilage nach Wahl (A, L)</note>
          <price role='student'>3.00</price>
          <price role='employee'>4.6</price>
          <price role='other'>4.6</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Erbseneintopf mit Würstchen</name>
          <note>mit Bauernbrot (2, 3, 5, I)</note>
          <price role='student'>2.00</price>
          <price role='employee'>3.6</price>
          <price role='other'>3.6</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Frankfurter Apfelweinbraten</name>
          <note>und zwei Beilagen nach Wahl (L)</note>
          <price role='student'>3.80</price>
          <price role='employee'>5.4</price>
          <price role='other'>5.4</price>
        </meal>
      </category>
      <category name='Essen 5'>
        <meal>
          <name>Kartoffel-Lauchsuppe</name>
          <note>(5, I)</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 6'>
        <meal>
          <name>Rindfleischfrikadelle</name>
          <note>Rahmwirsing und einer Beilage nach Wahl (A, C)</note>
          <price role='student'>2.30</price>
          <price role='employee'>3.9</price>
          <price role='other'>3.9</price>
        </meal>
      </category>
    </day>
    <day date='2015-02-03'>
      <category name='Essen 1'>
        <meal>
          <name>Gulasch Berliner Art</name>
          <note>Zöpflinudeln und einer Beilage nach Wahl</note>
          <price role='student'>3.20</price>
          <price role='employee'>4.8</price>
          <price role='other'>4.8</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Hirse-Käsetaler</name>
          <note>mit Sauce Vegetale und einer Beilage nach Wahl (A, C, F, G, I)</note>
          <price role='student'>2.00</price>
          <price role='employee'>3.6</price>
          <price role='other'>3.6</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Trierer Bohnensuppe</name>
          <note>(2, F, G, I)</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Ungarische Hähnchenkeule</name>
          <note>mit Geflügelsauce und zwei Beilagen nach Wahl (C, G)</note>
          <price role='student'>3.20</price>
          <price role='employee'>4.8</price>
          <price role='other'>4.8</price>
        </meal>
      </category>
    </day>
    <day date='2015-02-04'>
      <category name='Essen 1'>
        <meal>
          <name>Hokifilet mit Blattspinat</name>
          <note>und zwei Beilagen nach Wahl (A, D, G, I)</note>
          <price role='student'>4.40</price>
          <price role='employee'>6</price>
          <price role='other'>6</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Kirschpfannkuchen</name>
          <note>mit Vanillesauce und einer Beilage nach Wahl (A, C, G)</note>
          <price role='student'>2.50</price>
          <price role='employee'>4.1</price>
          <price role='other'>4.1</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Paprikasuppe</name>
          <note>(I)</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Pizza Hawaii</name>
          <note>(2, 3, A, G)</note>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 5'>
        <meal>
          <name>Pizza Margherita</name>
          <note>(A, G)</note>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 6'>
        <meal>
          <name>Schweine Cordon Bleu</name>
          <note>mit Bratensauce und zwei Beilagen nach Wahl (A, C, G, I)</note>
          <price role='student'>4.50</price>
          <price role='employee'>6.1</price>
          <price role='other'>6.1</price>
        </meal>
      </category>
      <category name='Essen 7'>
        <meal>
          <name>Schweinekotelett gefüllt mit Feta</name>
          <note>Kräuterbutter und einer Beilage nach Wahl (3, G)</note>
          <price role='student'>4.00</price>
          <price role='employee'>5.6</price>
          <price role='other'>5.6</price>
        </meal>
      </category>
    </day>
    <day date='2015-02-05'>
      <category name='Essen 1'>
        <meal>
          <name>Gemüse-Tomatensuppe</name>
          <note>(F, I)</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Gemüseauflauf</name>
          <note>und einer Beilage nach Wahl (5, A, G, I, J)</note>
          <price role='student'>1.90</price>
          <price role='employee'>3.5</price>
          <price role='other'>3.5</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Pizza Salami</name>
          <note>(2, 3, A, I, J, G)</note>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Pizza Spinat</name>
          <note>(3, A, G)</note>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 5'>
        <meal>
          <name>Tiroler Gröstl</name>
          <note>und einer Beilage nach Wahl (5, F, I)</note>
          <price role='student'>3.00</price>
          <price role='employee'>4.6</price>
          <price role='other'>4.6</price>
        </meal>
      </category>
      <category name='Essen 6'>
        <meal>
          <name>Wildschweinbratwurst</name>
          <note>mit Apfelrotkohl und einer Beilage nach Wahl (I)</note>
          <price role='student'>2.90</price>
          <price role='employee'>4.5</price>
          <price role='other'>4.5</price>
        </meal>
      </category>
    </day>
    <day date='2015-02-06'>
      <category name='Essen 1'>
        <meal>
          <name>Bunte Gemüsesuppe</name>
          <note>(I)</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Florentiner Hähnchenbrust</name>
          <note>mit Pfefferrahmsauce und zwei Beilagen nach Wahl (A, G)</note>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Kichererbsen-Kartoffelcurry</name>
          <note>und zwei Beilagen nach Wahl (5, I)</note>
          <price role='student'>1.90</price>
          <price role='employee'>3.5</price>
          <price role='other'>3.5</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Paniertes Schollenfilet</name>
          <note>mit Remouladensauce und einer Beilage nach Wahl (A, D)</note>
          <price role='student'>3.60</price>
          <price role='employee'>5.2</price>
          <price role='other'>5.2</price>
        </meal>
      </category>
    </day>
    <day date='2015-02-07'>
      <category name='Essen 1'>
        <meal>
          <name>Bunte Gemüsesuppe</name>
          <note>(I)</note>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>China-Gemüseschnitte mit</name>
          <note>Curryrahmsauce und zwei Beilagen nach Wahl (A, G, I, J)</note>
          <price role='student'>2.60</price>
          <price role='employee'>4.2</price>
          <price role='other'>4.2</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Rindfleischbällchen</name>
          <note>mit Rahmsauce und einer Beilage nach Wahl</note>
          <price role='student'>3.30</price>
          <price role='employee'>4.9</price>
          <price role='other'>4.9</price>
        </meal>
      </category>
    </day>

  </canteen>
</openmensa>

=== gsauthof/openmensa/test/ref/fhrus_20150216.xml
<?xml version="1.0" encoding="UTF-8"?>
<openmensa version="2.0"
           xmlns="http://openmensa.org/open-mensa-v2"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://openmensa.org/open-mensa-v2 http://openmensa.org/open-mensa-v2.xsd">
  <canteen>
    <day date='2015-02-16'>
      <category name='Essen 1'>
        <meal>
          <name>Kartoffel-Lauchsuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Gemüsekroketten</name>
          <note>mit Tomatensauce</note>
          <price role='student'>2.40</price>
          <price role='employee'>4</price>
          <price role='other'>4</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Bratwurst</name>
          <note>mit Curry-Ketchupsauce</note>
          <price role='student'>3.00</price>
          <price role='employee'>4.6</price>
          <price role='other'>4.6</price>
        </meal>
      </category>
    </day>
    <day date='2015-02-17'>
      <category name='Essen 1'>
        <meal>
          <name>Tomatencremesuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Reibekuchen</name>
          <note>mit Apfelmus und einer Beilage nach Wahl</note>
          <price role='student'>2.00</price>
          <price role='employee'>3.6</price>
          <price role='other'>3.6</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Kohlroulade</name>
          <note>mit Zwiebelsauce und zwei Beilagen nach Wahl</note>
          <price role='student'>2.50</price>
          <price role='employee'>4.1</price>
          <price role='other'>4.1</price>
        </meal>
      </category>
    </day>
    <day date='2015-02-18'>
      <category name='Essen 1'>
        <meal>
          <name>Paprikasuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>China-Gemüseschnitte</name>
          <note>mit Curry-Fruchtsauce</note>
          <price role='student'>2.80</price>
          <price role='employee'>4.4</price>
          <price role='other'>4.4</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Geflügelfrikadelle</name>
          <note>mit Pfefferrahmsauce</note>
          <price role='student'>2.70</price>
          <price role='employee'>4.3</price>
          <price role='other'>4.3</price>
        </meal>
      </category>
    </day>
    <day date='2015-02-19'>
      <category name='Essen 1'>
        <meal>
          <name>Gemüse-Tomatensuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Vollkornnudeln mit Zucchini und Schafskäse</name>
          <note>und einer Beilage nach Wahl</note>
          <price role='student'>2.60</price>
          <price role='employee'>4.2</price>
          <price role='other'>4.2</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>berbackene Hähnchenbrust mit Broccoli</name>
          <note>mit Geflügelsauce</note>
          <price role='student'>3.20</price>
          <price role='employee'>4.8</price>
          <price role='other'>4.8</price>
        </meal>
      </category>
    </day>
    <day date='2015-02-20'>
      <category name='Essen 1'>
        <meal>
          <name>Bunte Gemüsesuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Paprika-Kartoffelauflauf</name>
          <price role='student'>2.00</price>
          <price role='employee'>3.6</price>
          <price role='other'>3.6</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Kartoffelgulasch mit Würstchen</name>
          <note>und einer Beilage nach Wahl</note>
          <price role='student'>3.00</price>
          <price role='employee'>4.6</price>
          <price role='other'>4.6</price>
        </meal>
      </category>
    </day>

  </canteen>
</openmensa>
