=== gsauthof/openmensa/open-mensa-v2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://openmensa.org/open-mensa-v2" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://openmensa.org/open-mensa-v2" elementFormDefault="qualified">

    <xs:element name="openmensa" type="openmensaType"></xs:element>
    
    <xs:complexType name="openmensaType">
        <xs:annotation>
        	<xs:documentation>This is the required OpenMense root element always accompanied by a version attribute that explicitly tells the feed's version to the parser.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
    		<xs:element name="canteen" type="canteenType">
    		</xs:element>
    	</xs:sequence>
    	<xs:attribute name="version" type="xs:float" use="required">
    		<xs:annotation>
    			<xs:documentation>The version should be equal to 2.0.</xs:documentation>
    		</xs:annotation></xs:attribute>
    </xs:complexType>

    <xs:complexType name="canteenType">
        <xs:annotation>
        	<xs:documentation>This stands for a single canteen.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="day" type="dayType" maxOccurs="unbounded"
    			minOccurs="0">
                <xs:annotation>
                	<xs:documentation>All meals of all categories are grouped by day. There may be no day elements at all - that's ok because for some days there are no meals.</xs:documentation>
                </xs:annotation>
            </xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="dayType">
        <xs:choice>
        	<xs:element name="category" type="categoryType"
        		maxOccurs="unbounded" minOccurs="1">
        		<xs:annotation>
        			<xs:documentation>Every meal must belong to a category so there should be at least one category since a day without any meals may be omitted completely else.</xs:documentation>
        		</xs:annotation>
        	</xs:element>
        	<xs:element name="closed">
                <xs:annotation>
                	<xs:documentation>Indicates that for the given day a canteen has closed (to distinguish from the case where there is - for some reason - no data). Should be used on weekends or explicit closing times on holidays.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
        			<xs:restriction base="xs:string">
        				<xs:maxLength value="0"></xs:maxLength>
        			</xs:restriction>
        		</xs:simpleType>
        	</xs:element>
        </xs:choice>
    	<xs:attribute name="date" use="required">
            <xs:annotation>
            	<xs:documentation>This field specifies the date of the day as "YYYY-MM-DD.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
                <xs:annotation>
                	<xs:documentation></xs:documentation>
                </xs:annotation>
                <xs:restriction base="xs:string">
    				<xs:pattern
    					value="[0-9]{4,4}-[0-9]{2,2}-[0-9]{2,2}">
    				</xs:pattern>
    			</xs:restriction>
    		</xs:simpleType>
    	</xs:attribute>
    </xs:complexType>

    <xs:complexType name="categoryType">
    	<xs:sequence>
    		<xs:element name="meal" type="mealType" maxOccurs="unbounded" minOccurs="1">
    			<xs:annotation>
    				<xs:documentation>Each category must contain at least one meal because else the category is useless.</xs:documentation>
    			</xs:annotation></xs:element>
    	</xs:sequence>
    	<xs:attribute name="name" use="required">
            <xs:annotation>
            	<xs:documentation>The name of the category, e.g. "Essen 1" or "Ausgabe A".</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
            	<xs:restriction base="xs:string">
            		<xs:minLength value="1"></xs:minLength>
            		<xs:maxLength value="250"></xs:maxLength>
            	</xs:restriction>
            </xs:simpleType>
    	</xs:attribute>
    </xs:complexType>

    <xs:complexType name="mealType">
    	<xs:sequence>
    		<xs:element name="name">
    			<xs:annotation>
    				<xs:documentation>The name of the meal, e.g. "Rinderhacksteak mit Kartoffeln". Shouldn't be more than a couple of words or a sentence in maximum. Additional text may go into several notes.</xs:documentation>
    			</xs:annotation>
    			<xs:simpleType>
    				<xs:restriction base="xs:string">
    					<xs:minLength value="1"></xs:minLength>
    					<xs:maxLength value="250"></xs:maxLength>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="note" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                	<xs:documentation>A note often resembles a properties of the associated meal like the ingredients used or some important annotations.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                	<xs:restriction base="xs:string">
                		<xs:minLength value="1"></xs:minLength>
                		<xs:maxLength value="250"></xs:maxLength>
                	</xs:restriction>
                </xs:simpleType>
    		</xs:element>
    		<xs:element name="price" maxOccurs="unbounded" minOccurs="0" type="priceType">
                <xs:annotation>
                	<xs:documentation>This field contains a price in euro for a given role (because different prices may apply different groups of people). There mustn't be two price elements with the same role for a meal!</xs:documentation>
                </xs:annotation>
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="priceType">
    	<xs:simpleContent>
    		<xs:extension base="xs:float">
    			<xs:attribute name="role" use="required">
                    <xs:annotation>
                    	<xs:documentation>A price's role defines for which group of persons the price is valid:
- pupils (some canteens do that)
- students
- employees (of your organization) or
- others (people that do not belong to your organization or to any other group listed here).</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                    	<xs:restriction base="xs:string">
                    		<xs:enumeration value="pupil"></xs:enumeration>
                    		<xs:enumeration value="student"></xs:enumeration>
                    		<xs:enumeration value="employee"></xs:enumeration>
                    		<xs:enumeration value="other"></xs:enumeration>
                    	</xs:restriction>
                    </xs:simpleType>
    			</xs:attribute>
    		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== gsauthof/openmensa/test/ref/fhrus_20151124.xml
<?xml version="1.0" encoding="UTF-8"?>
<openmensa version="2.0"
           xmlns="http://openmensa.org/open-mensa-v2"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://openmensa.org/open-mensa-v2 http://openmensa.org/open-mensa-v2.xsd">
  <canteen>
    <day date='2015-11-23'>
      <category name='Essen 1'>
        <meal>
          <name>Kürbiscremesuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Kartoffel-Blumenkohlpfanne</name>
          <note>mit Pfefferrahmsauce (3, F) und einer Beilage nach Wahl</note>
          <price role='student'>2.20</price>
          <price role='employee'>3.8</price>
          <price role='other'>3.8</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Linseneintopf</name>
          <note>mit Wiener Würstchen (2, 3, I) und einem Kaiserbrötchen (A)</note>
          <price role='student'>2.10</price>
          <price role='employee'>3.7</price>
          <price role='other'>3.7</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Ebly-Gemüsepfanne</name>
          <note>mit Pfefferrahmsauce (3, F)</note>
          <price role='student'>2.00</price>
          <price role='employee'>3.6</price>
          <price role='other'>3.6</price>
        </meal>
      </category>
      <category name='Essen 5'>
        <meal>
          <name>Geflügeleintopf Portugiesisch</name>
          <note>mit Kaiserbrötchen (A)</note>
          <price role='student'>2.10</price>
          <price role='employee'>3.7</price>
          <price role='other'>3.7</price>
        </meal>
      </category>
      <category name='Essen 6'>
        <meal>
          <name>Truthahncevapcici</name>
          <note>mit Pusztasauce (2, 9, J) und zwei Beilagen nach Wahl</note>
          <price role='student'>3.20</price>
          <price role='employee'>4.8</price>
          <price role='other'>4.8</price>
        </meal>
      </category>
    </day>
    <day date='2015-11-24'>
      <category name='Essen 1'>
        <meal>
          <name>Kohlrabicremesuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>China-Gemüseschnitte</name>
          <note>mit Curry-Fruchtsauce (F, G, J) und einer Beilage nach Wahl</note>
          <price role='student'>2.20</price>
          <price role='employee'>3.8</price>
          <price role='other'>3.8</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Feuriges Schweinegulasch</name>
          <note>mit Fusilli (A) und einer Beilage nach Wahl</note>
          <price role='student'>3.40</price>
          <price role='employee'>5</price>
          <price role='other'>5</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Hähnchenknusperfilet</name>
          <note>mit Pilzrahmsauce (G) und einer Beilage nach Wahl</note>
          <price role='student'>2.90</price>
          <price role='employee'>4.5</price>
          <price role='other'>4.5</price>
        </meal>
      </category>
      <category name='Essen 5'>
        <meal>
          <name>Geflügelfrikadelle</name>
          <note>mit Pilzrahmsauce (G) und einer Beilage nach Wahl</note>
          <price role='student'>2.00</price>
          <price role='employee'>3.6</price>
          <price role='other'>3.6</price>
        </meal>
      </category>
      <category name='Essen 6'>
        <meal>
          <name>Pizza Champignon</name>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 7'>
        <meal>
          <name>Pizza Hawaii</name>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
    </day>
    <day date='2015-11-25'>
      <category name='Essen 1'>
        <meal>
          <name>Tschechische Knoblauch-Kartoffelsuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Champignon-Gemüsepfanne</name>
          <note>mit Vollkornreis (F) und einer Beilage nach Wahl</note>
          <price role='student'>2.10</price>
          <price role='employee'>3.7</price>
          <price role='other'>3.7</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Seelachsfilet mit Gemüsestreifen</name>
          <note>und einer Beilage nach Wahl</note>
          <price role='student'>3.90</price>
          <price role='employee'>5.5</price>
          <price role='other'>5.5</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Paniertes Schweineschnitzel</name>
          <note>mit Zwiebelsauce und zwei Beilagen nach Wahl</note>
          <price role='student'>3.00</price>
          <price role='employee'>4.6</price>
          <price role='other'>4.6</price>
        </meal>
      </category>
    </day>
    <day date='2015-11-26'>
      <category name='Essen 1'>
        <meal>
          <name>Frischkäsesuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Mais-Lauchplätzchen</name>
          <note>mit Gorgonzolarahmsauce (G) und einer Beilage nach Wahl</note>
          <price role='student'>3.40</price>
          <price role='employee'>5</price>
          <price role='other'>5</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Gefüllte Paprikaschote</name>
          <note>mit Tomatensauce und einer Beilage nach Wahl</note>
          <price role='student'>2.30</price>
          <price role='employee'>3.9</price>
          <price role='other'>3.9</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Schweineschulterbraten</name>
          <note>mit Zwiebelsauce und einer Beilage nach Wahl</note>
          <price role='student'>2.80</price>
          <price role='employee'>4.4</price>
          <price role='other'>4.4</price>
        </meal>
      </category>
      <category name='Essen 5'>
        <meal>
          <name>Gebratenes Hähnchenfleisch mit Gemüse</name>
          <note>und Basmatireis</note>
          <price role='student'>4.00</price>
          <price role='employee'>5.6</price>
          <price role='other'>5.6</price>
        </meal>
      </category>
    </day>
    <day date='2015-11-27'>
      <category name='Essen 1'>
        <meal>
          <name>Karotten-Ingwercremesuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Sojaragout</name>
          <note>mit Glasnudeln</note>
          <price role='student'>1.90</price>
          <price role='employee'>3.5</price>
          <price role='other'>3.5</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Seelachsfilet in Sesampanade</name>
          <note>mit Remouladensauce (2, 9, A, C, G, J) und einer Beilage nach Wahl</note>
          <price role='student'>3.40</price>
          <price role='employee'>5</price>
          <price role='other'>5</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Schweinerippchen</name>
          <note>mit Sauerkraut (F) und einer Beilage nach Wahl</note>
          <price role='student'>3.60</price>
          <price role='employee'>5.2</price>
          <price role='other'>5.2</price>
        </meal>
      </category>
    </day>
    <day date='2015-11-28'>
      <category name='Essen 1'>
        <meal>
          <name>Karotten-Ingwercremesuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Gemüseschnitzel</name>
          <note>mit Tomatensauce und einer Beilage nach Wahl</note>
          <price role='student'>1.60</price>
          <price role='employee'>3.2</price>
          <price role='other'>3.2</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Hähnchen Cordon bleu</name>
          <note>mit Geflügelsauce und einer Beilage nach Wahl</note>
          <price role='student'>2.50</price>
          <price role='employee'>4.1</price>
          <price role='other'>4.1</price>
        </meal>
      </category>
    </day>

  </canteen>
</openmensa>

=== gsauthof/openmensa/test/ref/fhrus_20160504.xml
<?xml version="1.0" encoding="UTF-8"?>
<openmensa version="2.0"
           xmlns="http://openmensa.org/open-mensa-v2"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://openmensa.org/open-mensa-v2 http://openmensa.org/open-mensa-v2.xsd">
  <canteen>
    <day date='2015-05-02'>
      <category name='Essen 1'>
        <meal>
          <name>Maissuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Nudel-Gemüsegratin</name>
          <note>mit Tomatensauce und einer Beilage nach Wahl</note>
          <price role='student'>1.80</price>
          <price role='employee'>3.4</price>
          <price role='other'>3.4</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Linseneintopf</name>
          <note>mit Wiener Würstchen (2, 3, I) mit Kaiserbrötchen (A)</note>
          <price role='student'>2.10</price>
          <price role='employee'>3.7</price>
          <price role='other'>3.7</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Sojabolognese</name>
          <note>mit zwei Beilagen nach Wahl</note>
          <price role='student'>2.10</price>
          <price role='employee'>3.7</price>
          <price role='other'>3.7</price>
        </meal>
      </category>
      <category name='Essen 5'>
        <meal>
          <name>Rindfleischfrikadelle</name>
          <note>mit Champignonrahmsauce (G) und zwei Beilagen nach Wahl</note>
          <price role='student'>3.50</price>
          <price role='employee'>5.1</price>
          <price role='other'>5.1</price>
        </meal>
      </category>
      <category name='Essen 6'>
        <meal>
          <name>Chili con Carne</name>
          <note>mit Baguette (A) und einer Beilage nach Wahl</note>
          <price role='student'>3.10</price>
          <price role='employee'>4.7</price>
          <price role='other'>4.7</price>
        </meal>
      </category>
    </day>
    <day date='2015-05-03'>
      <category name='Essen 1'>
        <meal>
          <name>Kohlrabicremesuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Gemüsesugo</name>
          <note>mit zwei Beilagen nach Wahl</note>
          <price role='student'>2.20</price>
          <price role='employee'>3.8</price>
          <price role='other'>3.8</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Hähnchenbrust Kiew</name>
          <note>mit Zwiebelsauce und zwei Beilagen nach Wahl</note>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Kohlroulade</name>
          <note>mit Specksauce (2) und einer Beilage nach Wahl</note>
          <price role='student'>1.70</price>
          <price role='employee'>3.3</price>
          <price role='other'>3.3</price>
        </meal>
      </category>
      <category name='Essen 5'>
        <meal>
          <name>Putenbrustfilet Orientalische Art</name>
          <note>mit einer Beilage nach Wahl</note>
          <price role='student'>3.20</price>
          <price role='employee'>4.8</price>
          <price role='other'>4.8</price>
        </meal>
      </category>
      <category name='Essen 6'>
        <meal>
          <name>Hähnchenpfanne mit Bambus</name>
          <note>mit Basmatireis</note>
          <price role='student'>4.00</price>
          <price role='employee'>5.6</price>
          <price role='other'>5.6</price>
        </meal>
      </category>
    </day>
    <day date='2015-05-04'>
      <category name='Essen 1'>
        <meal>
          <name>Oberhessische Kartoffelsuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Frühlingsrolle</name>
          <note>mit Curryrahmsauce (G, J) und einer Beilage nach Wahl</note>
          <price role='student'>1.80</price>
          <price role='employee'>3.4</price>
          <price role='other'>3.4</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Kasslerbraten</name>
          <note>mit Rotweinsauce (L) und einer Beilage nach Wahl</note>
          <price role='student'>3.30</price>
          <price role='employee'>4.9</price>
          <price role='other'>4.9</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Putenragout im Tomatensud</name>
          <note>und einer Beilage nach Wahl</note>
          <price role='student'>3.50</price>
          <price role='employee'>5.1</price>
          <price role='other'>5.1</price>
        </meal>
      </category>
      <category name='Essen 5'>
        <meal>
          <name>Pizza Salami</name>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 6'>
        <meal>
          <name>Pizza Spinat</name>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
    </day>
    <day date='2015-05-06'>
      <category name='Essen 1'>
        <meal>
          <name>Würzige Tomatensuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Tortellini mit Spinat-Käsefüllung</name>
          <note>mit Sauce Napoli mit Paprika-Tomatensauce</note>
          <price role='student'>1.60</price>
          <price role='employee'>3.2</price>
          <price role='other'>3.2</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Bratwurst</name>
          <note>mit Bratensauce und zwei Beilagen nach Wahl</note>
          <price role='student'>3.10</price>
          <price role='employee'>4.7</price>
          <price role='other'>4.7</price>
        </meal>
      </category>
      <category name='Essen 4'>
        <meal>
          <name>Paniertes Seelachsfilet</name>
          <note>mit Joghurt-Dillsauce (G) und zwei Beilagen nach Wahl</note>
          <price role='student'>3.90</price>
          <price role='employee'>5.5</price>
          <price role='other'>5.5</price>
        </meal>
      </category>
    </day>
    <day date='2015-05-07'>
      <category name='Essen 1'>
        <meal>
          <name>Würzige Tomatensuppe</name>
          <price role='student'>0.90</price>
          <price role='employee'>2.5</price>
          <price role='other'>2.5</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Kohlrabi mit Saurer Sahne und Kartoffeln</name>
          <price role='student'>1.60</price>
          <price role='employee'>3.2</price>
          <price role='other'>3.2</price>
        </meal>
      </category>
      <category name='Essen 3'>
        <meal>
          <name>Panierte Putenbrust</name>
          <note>mit Champignonrahmsauce (G) und zwei Beilagen nach Wahl</note>
          <price role='student'>4.00</price>
          <price role='employee'>5.6</price>
          <price role='other'>5.6</price>
        </meal>
      </category>
    </day>

  </canteen>
</openmensa>

=== gsauthof/openmensa/test/ref/fra_hfmdk_20160224.xml
<?xml version="1.0" encoding="UTF-8"?>
<openmensa version="2.0"
           xmlns="http://openmensa.org/open-mensa-v2"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://openmensa.org/open-mensa-v2 http://openmensa.org/open-mensa-v2.xsd">
  <canteen>
    <day date='2015-02-22'>
      <category name='Essen 1'>
        <meal>
          <name>Sojabolognese</name>
          <note>und zwei Beilagen nach Wahl</note>
          <note>Vegan</note>
          <price role='student'>2.50</price>
          <price role='employee'>4.1</price>
          <price role='other'>4.1</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Hähnchenbruststreifen mit Rucolasauce</name>
          <note>und Tomaten-Bandnudeln (A, C)</note>
          <note>MensaVital</note>
          <price role='student'>3.80</price>
          <price role='employee'>5.4</price>
          <price role='other'>5.4</price>
        </meal>
      </category>
    </day>
    <day date='2015-02-23'>
      <category name='Essen 1'>
        <meal>
          <name>Bifteki</name>
          <note>mit Diavolosauce (G) und einer Beilage nach Wahl</note>
          <note>Rind</note>
          <price role='student'>3.70</price>
          <price role='employee'>5.3</price>
          <price role='other'>5.3</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Makkaroni-Tomatenauflauf</name>
          <note>MensaVital</note>
          <note>vegetarisch</note>
          <price role='student'>2.20</price>
          <price role='employee'>3.8</price>
          <price role='other'>3.8</price>
        </meal>
      </category>
    </day>
    <day date='2015-02-24'>
      <category name='Essen 1'>
        <meal>
          <name>Broccoli-Nussecke</name>
          <note>mit Sauce Napoli und einer Beilage nach Wahl</note>
          <note>Vegan</note>
          <price role='student'>2.00</price>
          <price role='employee'>3.6</price>
          <price role='other'>3.6</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Gedünstetes Seelachsfilet</name>
          <note>mit glasierten Möhren (G, L) und Dillkartoffeln (5)</note>
          <note>MensaVital</note>
          <note>MSC-Fisch</note>
          <price role='student'>5.00</price>
          <price role='employee'>6.6</price>
          <price role='other'>6.6</price>
        </meal>
      </category>
    </day>
    <day date='2015-02-25'>
      <category name='Essen 1'>
        <meal>
          <name>Kesselgulasch</name>
          <note>und zwei Beilagen nach Wahl</note>
          <note>Schwein</note>
          <note>Alkohol</note>
          <price role='student'>4.20</price>
          <price role='employee'>5.8</price>
          <price role='other'>5.8</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Gemüsepaella mit Walnüssen</name>
          <note>MensaVital</note>
          <note>Vegan</note>
          <note>Alkohol</note>
          <price role='student'>2.50</price>
          <price role='employee'>4.1</price>
          <price role='other'>4.1</price>
        </meal>
      </category>
    </day>
    <day date='2015-02-26'>
      <category name='Essen 1'>
        <meal>
          <name>Paniertes Seelachsfilet</name>
          <note>mit Dillsauce (G) und einer Beilage nach Wahl</note>
          <note>MSC-Fisch</note>
          <price role='student'>3.00</price>
          <price role='employee'>4.6</price>
          <price role='other'>4.6</price>
        </meal>
      </category>
      <category name='Essen 2'>
        <meal>
          <name>Schupfnudel-Gemüsepfanne</name>
          <note>MensaVital</note>
          <note>vegetarisch</note>
          <price role='student'>2.70</price>
          <price role='employee'>4.3</price>
          <price role='other'>4.3</price>
        </meal>
      </category>
    </day>

  </canteen>
</openmensa>
